services:
    - type: web
      name: sample-render  
      runtime: docker         
      plan: free         
      rootDir: ./src/Render.Api
      autoDeploy: true              
      branch: master 
      dockerContext: .
      dockerfilePath: Dockerfile