services:
    - type: web
      name: sample-render  
      runtime: docker         
      plan: free                    
      autoDeploy: true              
      branch: master 
      dockerContext: ./src/Render.Api
      dockerfilePath: Dockerfile